name: Desktop
on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hifini:
    permissions:
      contents: write
      actions: write
      attestations: write
      deployments: write
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sync node version and setup cache
      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: pnpm install

      - name: Install dependencies
        run: |
          npm ci  # 安装项目依赖
          npx puppeteer browsers install chrome  # 显式安装 Chrome

      - name: Run hifini script
        run: node src/hifini.js

      - name: Print result
        shell: bash
        run: |
          # 读取当前配置
          RESULT_FILE="result.txt"
          # 显示更新后的配置
          cat $RESULT_FILE

  netease:
    needs: hifini
    permissions:
      contents: write
      actions: write
      attestations: write
      deployments: write
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sync node version and setup cache
      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: pnpm install

  qq:
    needs: netease
    permissions:
      contents: write
      actions: write
      attestations: write
      deployments: write
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sync node version and setup cache
      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: pnpm install

  kuwo:
    needs: qq
    permissions:
      contents: write
      actions: write
      attestations: write
      deployments: write
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Sync node version and setup cache
      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: pnpm install
